# UpDesk - Ultra Simple Test Version for Portainer
# Use this to test if the basic image works in your Portainer setup

version: '3.3'

services:
  updesk:
    image: uptecps/updesk:latest
    ports:
      - "5002:5002"
    environment:
      NODE_ENV: production
    restart: unless-stopped