version: '3.8'

# UpDesk Virtual Desktop Launcher - Apache Version
# GitHub: https://github.com/uptec-ps/updesk
# Docker Hub: uptecps/updesk

services:
  updesk:
    # Build from local source (for development)
    build:
      context: .
      dockerfile: Dockerfile
    # Alternative: Build directly from GitHub (uncomment to use)
    # build: https://github.com/uptec-ps/updesk.git
    # Alternative: Use pre-built image from Docker Hub (uncomment to use)
    # image: uptecps/updesk:latest
    container_name: updesk-app
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - PORT=5002
    volumes:
      # Persist SQLite database
      - updesk_data:/app/data
      # Share static files with Apache
      - updesk_static:/app/dist
      # Optional: Mount custom wallpapers
      - ./public/wallpapers:/app/public/wallpapers:ro
      # Optional: Mount custom icons
      - ./public/icons:/app/public/icons:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5002/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.updesk.description=UpDesk Virtual Desktop Launcher"
      - "com.updesk.version=1.0.0"
    networks:
      - updesk_network

  # Apache reverse proxy for HTTP and HTTPS
  apache:
    image: httpd:2.4-alpine
    container_name: updesk-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache.conf:/usr/local/apache2/conf/extra/updesk.conf:ro
      - ./apache-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./ssl:/usr/local/apache2/ssl:ro
      # Mount static files from updesk container for direct serving
      - updesk_static:/usr/local/apache2/htdocs:ro
    depends_on:
      - updesk
    restart: unless-stopped
    networks:
      - updesk_network
    labels:
      - "com.updesk.description=Apache reverse proxy for UpDesk"

volumes:
  updesk_data:
    driver: local
    labels:
      - "com.updesk.description=UpDesk SQLite database storage"
  updesk_static:
    driver: local
    labels:
      - "com.updesk.description=UpDesk static files (frontend build)"

networks:
  updesk_network:
    driver: bridge
    labels:
      - "com.updesk.description=UpDesk application network"